steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: sh
    args: ["-c", "docker pull $_IMAGE_API || true"]
  - name: gcr.io/cloud-builders/docker
    env: ["DOCKER_BUILDKIT=1"]
    args:
      [
        "build",
        "--build-arg",
        "BUILDKIT_INLINE_CACHE=1",
        "--build-arg",
        "CACHE_BUST=$_CACHE_BUST",
        "--cache-from",
        "$_IMAGE_API",
        "-t",
        "$_IMAGE_API",
        "apps/api",
      ]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE_API"]
  - name: gcr.io/cloud-builders/docker
    entrypoint: sh
    args: ["-c", "docker pull $_IMAGE_WORKER || true"]
  - name: gcr.io/cloud-builders/docker
    env: ["DOCKER_BUILDKIT=1"]
    args:
      [
        "build",
        "--build-arg",
        "BUILDKIT_INLINE_CACHE=1",
        "--build-arg",
        "CACHE_BUST=$_CACHE_BUST",
        "--cache-from",
        "$_IMAGE_WORKER",
        "-f",
        "apps/api/Dockerfile.worker",
        "-t",
        "$_IMAGE_WORKER",
        "apps/api",
      ]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE_WORKER"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["run", "jobs", "update", "$_MIGRATE_JOB", "--image", "$_IMAGE_API", "--region", "$_REGION", "--quiet"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["beta", "run", "jobs", "execute", "$_MIGRATE_JOB", "--region", "$_REGION", "--wait", "--quiet"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["run", "services", "update", "$_API_SERVICE", "--image", "$_IMAGE_API", "--region", "$_REGION", "--quiet"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["run", "services", "update", "$_WORKER_SERVICE", "--image", "$_IMAGE_WORKER", "--region", "$_REGION", "--quiet"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["run", "jobs", "update", "$_CLAMAV_UPDATE_JOB", "--image", "$_IMAGE_WORKER", "--region", "$_REGION", "--quiet"]
images:
  - "$_IMAGE_API"
  - "$_IMAGE_WORKER"
options:
  # BYOSA (build.service_account) requires Cloud Logging or an explicit logs bucket.
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: "us-central1"
  _API_SERVICE: "crm-api"
  _WORKER_SERVICE: "crm-worker"
  _MIGRATE_JOB: "crm-migrate"
  _CACHE_BUST: "0"
  _IMAGE_API: "us-central1-docker.pkg.dev/probable-dream-484923-n7/crm/api:latest"
  _IMAGE_WORKER: "us-central1-docker.pkg.dev/probable-dream-484923-n7/crm/worker:latest"
  _CLAMAV_UPDATE_JOB: "crm-clamav-update"
