steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_IMAGE_API", "apps/api"]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE_API"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["run", "services", "update", "$_API_SERVICE", "--image", "$_IMAGE_API", "--region", "$_REGION", "--quiet"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["run", "jobs", "update", "$_WORKER_JOB", "--image", "$_IMAGE_API", "--region", "$_REGION", "--quiet"]
images:
  - "$_IMAGE_API"
options:
  logging: GCS_ONLY
substitutions:
  _REGION: "us-central1"
  _API_SERVICE: "crm-api"
  _WORKER_JOB: "crm-worker"
  _IMAGE_API: "us-central1-docker.pkg.dev/probable-dream-484923-n7/crm/api:latest"
