"""SQLAlchemy ORM models for the application."""

from app.db.models.ai import (
    AIActionApproval,
    AIBulkTaskRequest,
    AIConversation,
    AIEntitySummary,
    AIMessage,
    AISettings,
    AIUsageLog,
)
from app.db.models.analytics import AnalyticsSnapshot, RequestMetricsRollup
from app.db.models.appointments import (
    Appointment,
    AppointmentEmailLog,
    AppointmentType,
    AvailabilityOverride,
    AvailabilityRule,
    BookingLink,
    ZoomMeeting,
    ZoomWebhookEvent,
)
from app.db.models.attachments import Attachment
from app.db.models.audit import AuditLog, DataRetentionPolicy, LegalHold
from app.db.models.auth import (
    AdminActionLog,
    AuthIdentity,
    Membership,
    OrgCounter,
    OrgInvite,
    Organization,
    OrganizationSubscription,
    RolePermission,
    SupportSession,
    User,
    UserPermissionOverride,
    UserSession,
)
from app.db.models.campaigns import Campaign, CampaignRecipient, CampaignRun, CampaignTrackingEvent
from app.db.models.email import EmailLog, EmailSuppression, EmailTemplate
from app.db.models.forms import (
    Form,
    FormFieldMapping,
    FormLogo,
    FormSubmission,
    FormSubmissionFile,
    FormSubmissionToken,
)
from app.db.models.integration_health import IntegrationErrorRollup, IntegrationHealth, SystemAlert
from app.db.models.integrations import (
    ResendSettings,
    UserIntegration,
    ZapierInboundWebhook,
    ZapierWebhookSettings,
)
from app.db.models.intended_parents import IntendedParent, IntendedParentStatusHistory
from app.db.models.jobs import ExportJob, Job
from app.db.models.matches import Match, MatchEvent
from app.db.models.meta import (
    MetaAd,
    MetaAdAccount,
    MetaAdSet,
    MetaCampaign,
    MetaDailySpend,
    MetaAdPlatformDaily,
    MetaForm,
    MetaFormVersion,
    MetaLead,
    MetaOAuthConnection,
    MetaPageMapping,
)
from app.db.models.notifications import Notification, UserNotificationSettings
from app.db.models.platform_templates import (
    PlatformBranding,
    PlatformEmailTemplate,
    PlatformEmailTemplateTarget,
    PlatformFormTemplate,
    PlatformFormTemplateTarget,
    PlatformSystemEmailTemplate,
)
from app.db.models.pipelines import EntityVersion, Pipeline, PipelineStage
from app.db.models.queues import Queue, QueueMember
from app.db.models.status_changes import StatusChangeRequest
from app.db.models.surrogates import (
    CustomField,
    CustomFieldValue,
    ImportMappingCorrection,
    ImportTemplate,
    InterviewAttachment,
    InterviewNote,
    InterviewTranscriptVersion,
    JourneyFeaturedImage,
    Surrogate,
    SurrogateActivityLog,
    SurrogateContactAttempt,
    SurrogateImport,
    SurrogateInterview,
    SurrogateProfileHiddenField,
    SurrogateProfileOverride,
    SurrogateProfileState,
    SurrogateStatusHistory,
)
from app.db.models.tasks import EntityNote, Task
from app.db.models.workflows import (
    AutomationWorkflow,
    UserWorkflowPreference,
    WorkflowExecution,
    WorkflowResumeJob,
    WorkflowTemplate,
    WorkflowTemplateTarget,
)

__all__ = [
    "AIActionApproval",
    "AIBulkTaskRequest",
    "AIConversation",
    "AIEntitySummary",
    "AIMessage",
    "AISettings",
    "AIUsageLog",
    "AdminActionLog",
    "AnalyticsSnapshot",
    "Appointment",
    "AppointmentEmailLog",
    "AppointmentType",
    "Attachment",
    "AuditLog",
    "AuthIdentity",
    "AutomationWorkflow",
    "AvailabilityOverride",
    "AvailabilityRule",
    "BookingLink",
    "Campaign",
    "CampaignRecipient",
    "CampaignRun",
    "CampaignTrackingEvent",
    "CustomField",
    "CustomFieldValue",
    "DataRetentionPolicy",
    "ImportMappingCorrection",
    "EmailLog",
    "EmailSuppression",
    "EmailTemplate",
    "EntityNote",
    "EntityVersion",
    "ExportJob",
    "Form",
    "FormFieldMapping",
    "FormLogo",
    "FormSubmission",
    "FormSubmissionFile",
    "FormSubmissionToken",
    "ImportTemplate",
    "IntegrationErrorRollup",
    "IntegrationHealth",
    "IntendedParent",
    "IntendedParentStatusHistory",
    "InterviewAttachment",
    "InterviewNote",
    "InterviewTranscriptVersion",
    "Job",
    "JourneyFeaturedImage",
    "LegalHold",
    "Match",
    "MatchEvent",
    "Membership",
    "MetaAd",
    "MetaAdAccount",
    "MetaAdSet",
    "MetaCampaign",
    "MetaDailySpend",
    "MetaAdPlatformDaily",
    "MetaForm",
    "MetaFormVersion",
    "MetaLead",
    "MetaOAuthConnection",
    "MetaPageMapping",
    "Notification",
    "OrgCounter",
    "OrgInvite",
    "Organization",
    "OrganizationSubscription",
    "Pipeline",
    "PipelineStage",
    "PlatformEmailTemplate",
    "PlatformEmailTemplateTarget",
    "PlatformFormTemplate",
    "PlatformFormTemplateTarget",
    "PlatformSystemEmailTemplate",
    "PlatformBranding",
    "Queue",
    "QueueMember",
    "RequestMetricsRollup",
    "ResendSettings",
    "ZapierInboundWebhook",
    "ZapierWebhookSettings",
    "RolePermission",
    "StatusChangeRequest",
    "SupportSession",
    "Surrogate",
    "SurrogateActivityLog",
    "SurrogateContactAttempt",
    "SurrogateImport",
    "SurrogateInterview",
    "SurrogateProfileHiddenField",
    "SurrogateProfileOverride",
    "SurrogateProfileState",
    "SurrogateStatusHistory",
    "SystemAlert",
    "Task",
    "User",
    "UserIntegration",
    "UserNotificationSettings",
    "UserPermissionOverride",
    "UserSession",
    "UserWorkflowPreference",
    "WorkflowExecution",
    "WorkflowResumeJob",
    "WorkflowTemplate",
    "WorkflowTemplateTarget",
    "ZoomMeeting",
    "ZoomWebhookEvent",
]
