// Generated by scripts/gen_surrogate_contracts.py. Do not edit.

export type SurrogateSource = "manual" | "meta" | "tiktok" | "google" | "website" | "referral" | "import" | "agency" | "other";

export interface SurrogateListItem {
    id: string;
    surrogate_number: string;
    stage_id: string;
    stage_slug?: string | null;
    stage_type?: string | null;
    status_label: string;
    source: SurrogateSource;
    full_name: string;
    email: string;
    phone: string | null;
    state: string | null;
    race?: string | null;
    owner_type?: string | null;
    owner_id?: string | null;
    owner_name?: string | null;
    is_priority: boolean;
    is_archived: boolean;
    age?: number | null;
    bmi?: number | null;
    last_activity_at?: string | null;
    created_at: string;
}

export interface SurrogateRead {
    id: string;
    surrogate_number: string;
    stage_id: string;
    status_label: string;
    source: SurrogateSource;
    is_priority: boolean;
    owner_type: string;
    owner_id: string;
    owner_name?: string | null;
    created_by_user_id: string | null;
    full_name: string;
    email: string;
    phone: string | null;
    state: string | null;
    date_of_birth: string | null;
    race: string | null;
    height_ft: string | null;
    weight_lb: number | null;
    is_age_eligible: boolean | null;
    is_citizen_or_pr: boolean | null;
    has_child: boolean | null;
    is_non_smoker: boolean | null;
    has_surrogate_experience: boolean | null;
    num_deliveries: number | null;
    num_csections: number | null;
    insurance_company?: string | null;
    insurance_plan_name?: string | null;
    insurance_phone?: string | null;
    insurance_policy_number?: string | null;
    insurance_member_id?: string | null;
    insurance_group_number?: string | null;
    insurance_subscriber_name?: string | null;
    insurance_subscriber_dob?: string | null;
    clinic_name?: string | null;
    clinic_address_line1?: string | null;
    clinic_address_line2?: string | null;
    clinic_city?: string | null;
    clinic_state?: string | null;
    clinic_postal?: string | null;
    clinic_phone?: string | null;
    clinic_email?: string | null;
    monitoring_clinic_name?: string | null;
    monitoring_clinic_address_line1?: string | null;
    monitoring_clinic_address_line2?: string | null;
    monitoring_clinic_city?: string | null;
    monitoring_clinic_state?: string | null;
    monitoring_clinic_postal?: string | null;
    monitoring_clinic_phone?: string | null;
    monitoring_clinic_email?: string | null;
    ob_provider_name?: string | null;
    ob_clinic_name?: string | null;
    ob_address_line1?: string | null;
    ob_address_line2?: string | null;
    ob_city?: string | null;
    ob_state?: string | null;
    ob_postal?: string | null;
    ob_phone?: string | null;
    ob_email?: string | null;
    delivery_hospital_name?: string | null;
    delivery_hospital_address_line1?: string | null;
    delivery_hospital_address_line2?: string | null;
    delivery_hospital_city?: string | null;
    delivery_hospital_state?: string | null;
    delivery_hospital_postal?: string | null;
    delivery_hospital_phone?: string | null;
    delivery_hospital_email?: string | null;
    pregnancy_start_date?: string | null;
    pregnancy_due_date?: string | null;
    actual_delivery_date?: string | null;
    delivery_baby_gender?: string | null;
    delivery_baby_weight?: string | null;
    is_archived: boolean;
    archived_at: string | null;
    created_at: string;
    updated_at: string;
}

export interface SurrogateListResponse {
    items: SurrogateListItem[];
    total?: number | null;
    page: number;
    per_page: number;
    pages?: number | null;
    next_cursor?: string | null;
}

export interface SurrogateStatusChange {
    stage_id: string;
    reason?: string | null;
    effective_at?: string | null;
    delivery_baby_gender?: string | null;
    delivery_baby_weight?: string | null;
}

export interface SurrogateStatusHistoryRead {
    id: string;
    from_stage_id: string | null;
    to_stage_id: string | null;
    from_label_snapshot: string | null;
    to_label_snapshot: string | null;
    changed_by_user_id: string | null;
    changed_by_name?: string | null;
    reason: string | null;
    changed_at: string;
    effective_at?: string | null;
    recorded_at?: string | null;
    requested_at?: string | null;
    approved_by_user_id?: string | null;
    approved_by_name?: string | null;
    approved_at?: string | null;
    is_undo?: boolean;
    request_id?: string | null;
}

export interface SurrogateStatusChangeResponse {
    status: string;
    surrogate?: SurrogateRead | null;
    request_id?: string | null;
    message?: string | null;
}

export type SurrogateStatusHistory = SurrogateStatusHistoryRead;
export type SurrogateStatusChangePayload = SurrogateStatusChange;
