"""add_thread_and_resolve_to_interview_notes

Revision ID: 670f828cdc71
Revises: 730b9f8b88f3
Create Date: 2026-01-06 16:27:02.052748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "670f828cdc71"
down_revision: Union[str, Sequence[str], None] = "730b9f8b88f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interview_notes", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.add_column(
        "interview_notes", sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column("interview_notes", sa.Column("resolved_by_user_id", sa.UUID(), nullable=True))
    op.create_index("ix_interview_notes_parent", "interview_notes", ["parent_id"], unique=False)
    op.create_foreign_key(
        None, "interview_notes", "interview_notes", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "interview_notes", "users", ["resolved_by_user_id"], ["id"])

    # Update constraint to allow anchor_text alone (without offsets) for comment_id anchoring
    op.drop_constraint("ck_interview_notes_anchor_complete", "interview_notes", type_="check")
    op.create_check_constraint(
        "ck_interview_notes_anchor_complete",
        "interview_notes",
        "(anchor_start IS NULL AND anchor_end IS NULL) OR "
        "(anchor_start IS NOT NULL AND anchor_end IS NOT NULL AND anchor_text IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore old constraint
    op.drop_constraint("ck_interview_notes_anchor_complete", "interview_notes", type_="check")
    op.create_check_constraint(
        "ck_interview_notes_anchor_complete",
        "interview_notes",
        "(anchor_start IS NULL AND anchor_end IS NULL AND anchor_text IS NULL) OR "
        "(anchor_start IS NOT NULL AND anchor_end IS NOT NULL AND anchor_text IS NOT NULL)",
    )

    op.drop_constraint(None, "interview_notes", type_="foreignkey")
    op.drop_constraint(None, "interview_notes", type_="foreignkey")
    op.drop_index("ix_interview_notes_parent", table_name="interview_notes")
    op.drop_column("interview_notes", "resolved_by_user_id")
    op.drop_column("interview_notes", "resolved_at")
    op.drop_column("interview_notes", "parent_id")
    # ### end Alembic commands ###
