"""add_contact_attempts_tracking

Revision ID: 890beee2b949
Revises: 2dfc2b083a5e
Create Date: 2026-01-03 23:23:24.504516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "890beee2b949"
down_revision: Union[str, Sequence[str], None] = "2dfc2b083a5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_contact_attempts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("attempted_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "contact_methods",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("case_owner_id_at_attempt", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "contact_methods <@ ARRAY['phone', 'email', 'sms']::VARCHAR[]",
            name="ck_contact_methods_valid",
        ),
        sa.CheckConstraint(
            "array_length(contact_methods, 1) > 0", name="ck_contact_methods_not_empty"
        ),
        sa.CheckConstraint(
            "attempted_at <= (now() + interval '5 minutes')", name="ck_attempted_at_not_future"
        ),
        sa.ForeignKeyConstraint(["attempted_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_contact_attempts_case",
        "case_contact_attempts",
        ["case_id", "attempted_at"],
        unique=False,
    )
    op.create_index(
        "idx_contact_attempts_case_owner",
        "case_contact_attempts",
        ["case_id", "case_owner_id_at_attempt", "attempted_at"],
        unique=False,
    )
    op.create_index(
        "idx_contact_attempts_org_pending",
        "case_contact_attempts",
        ["organization_id", "outcome", "attempted_at"],
        unique=False,
        postgresql_where=sa.text("outcome != 'reached'"),
    )
    op.add_column("cases", sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "cases",
        sa.Column(
            "contact_status",
            sa.String(length=20),
            server_default=sa.text("'unreached'"),
            nullable=False,
        ),
    )
    op.add_column("cases", sa.Column("contacted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "pipeline_stages",
        sa.Column("is_intake_stage", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
    )
    op.add_column(
        "user_notification_settings",
        sa.Column("contact_reminder", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )

    # Create index for reminder queries
    op.create_index(
        "idx_cases_reminder_check",
        "cases",
        ["organization_id", "owner_type", "contact_status", "stage_id"],
        unique=False,
        postgresql_where=sa.text(
            "is_archived = FALSE AND owner_type = 'user' AND contact_status = 'unreached'"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_cases_reminder_check",
        table_name="cases",
        postgresql_where=sa.text(
            "is_archived = FALSE AND owner_type = 'user' AND contact_status = 'unreached'"
        ),
    )
    op.drop_column("pipeline_stages", "is_intake_stage")
    op.drop_column("user_notification_settings", "contact_reminder")
    op.drop_column("cases", "contacted_at")
    op.drop_column("cases", "contact_status")
    op.drop_column("cases", "assigned_at")
    op.drop_index(
        "idx_contact_attempts_org_pending",
        table_name="case_contact_attempts",
        postgresql_where=sa.text("outcome != 'reached'"),
    )
    op.drop_index("idx_contact_attempts_case_owner", table_name="case_contact_attempts")
    op.drop_index("idx_contact_attempts_case", table_name="case_contact_attempts")
    op.drop_table("case_contact_attempts")
    # ### end Alembic commands ###
