"""Fix queue timestamp types

Revision ID: f3bc6a65a816
Revises: 0025_add_task_duration_minutes
Create Date: 2025-12-18 16:53:26.250999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f3bc6a65a816"
down_revision: Union[str, Sequence[str], None] = "0025_add_task_duration_minutes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_logs",
        "details",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(
        "idx_cases_meta_ad",
        "cases",
        ["organization_id", "meta_ad_id"],
        unique=False,
        postgresql_where=sa.text("meta_ad_id IS NOT NULL"),
        if_not_exists=True,
    )
    op.create_index(
        "idx_cases_meta_form",
        "cases",
        ["organization_id", "meta_form_id"],
        unique=False,
        postgresql_where=sa.text("meta_form_id IS NOT NULL"),
        if_not_exists=True,
    )
    op.alter_column(
        "queues",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "queues",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("tasks_created_by_user_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["created_by_user_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_created_by_user_id_fkey"),
        "tasks",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "queues",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "queues",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        "idx_cases_meta_form",
        table_name="cases",
        postgresql_where=sa.text("meta_form_id IS NOT NULL"),
    )
    op.drop_index(
        "idx_cases_meta_ad",
        table_name="cases",
        postgresql_where=sa.text("meta_ad_id IS NOT NULL"),
    )
    op.alter_column(
        "audit_logs",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
