// Generated by scripts/gen_stage_map.py. Do not edit.

import type { StageSemantics } from "@/lib/api/pipelines"

export type StageType = "intake" | "paused" | "post_approval" | "terminal"

export type StageDef = {
    stageKey: string
    slug: string
    label: string
    color: string
    order: number
    stageType: StageType
}

export const STAGE_DEFS: StageDef[] = [
    {
        "stageKey": "new_unread",
        "slug": "new_unread",
        "label": "New Unread",
        "color": "#3B82F6",
        "order": 1,
        "stageType": "intake"
    },
    {
        "stageKey": "contacted",
        "slug": "contacted",
        "label": "Contacted",
        "color": "#06B6D4",
        "order": 2,
        "stageType": "intake"
    },
    {
        "stageKey": "pre_qualified",
        "slug": "pre_qualified",
        "label": "Pre-Qualified",
        "color": "#10B981",
        "order": 3,
        "stageType": "intake"
    },
    {
        "stageKey": "application_submitted",
        "slug": "application_submitted",
        "label": "Application Submitted",
        "color": "#8B5CF6",
        "order": 4,
        "stageType": "intake"
    },
    {
        "stageKey": "interview_scheduled",
        "slug": "interview_scheduled",
        "label": "Interview Scheduled",
        "color": "#A855F7",
        "order": 5,
        "stageType": "intake"
    },
    {
        "stageKey": "pending_docusign",
        "slug": "pending_docusign",
        "label": "Pending-DocuSign",
        "color": "#F59E0B",
        "order": 6,
        "stageType": "intake"
    },
    {
        "stageKey": "under_review",
        "slug": "under_review",
        "label": "Under Review",
        "color": "#F59E0B",
        "order": 7,
        "stageType": "intake"
    },
    {
        "stageKey": "approved",
        "slug": "approved",
        "label": "Approved",
        "color": "#22C55E",
        "order": 8,
        "stageType": "intake"
    },
    {
        "stageKey": "ready_to_match",
        "slug": "ready_to_match",
        "label": "Ready to Match",
        "color": "#0EA5E9",
        "order": 9,
        "stageType": "post_approval"
    },
    {
        "stageKey": "matched",
        "slug": "matched",
        "label": "Matched",
        "color": "#6366F1",
        "order": 10,
        "stageType": "post_approval"
    },
    {
        "stageKey": "medical_clearance_passed",
        "slug": "medical_clearance_passed",
        "label": "Medical Clearance Passed",
        "color": "#14B8A6",
        "order": 11,
        "stageType": "post_approval"
    },
    {
        "stageKey": "legal_clearance_passed",
        "slug": "legal_clearance_passed",
        "label": "Legal Clearance Passed",
        "color": "#059669",
        "order": 12,
        "stageType": "post_approval"
    },
    {
        "stageKey": "transfer_cycle",
        "slug": "transfer_cycle",
        "label": "Transfer Cycle Initiated",
        "color": "#0D9488",
        "order": 13,
        "stageType": "post_approval"
    },
    {
        "stageKey": "second_hcg_confirmed",
        "slug": "second_hcg_confirmed",
        "label": "Second hCG confirmed",
        "color": "#10B981",
        "order": 14,
        "stageType": "post_approval"
    },
    {
        "stageKey": "heartbeat_confirmed",
        "slug": "heartbeat_confirmed",
        "label": "Heartbeat Confirmed",
        "color": "#22C55E",
        "order": 15,
        "stageType": "post_approval"
    },
    {
        "stageKey": "life_insurance_application_started",
        "slug": "life_insurance_application_started",
        "label": "Life Insurance Application Started",
        "color": "#0891B2",
        "order": 16,
        "stageType": "post_approval"
    },
    {
        "stageKey": "ob_care_established",
        "slug": "ob_care_established",
        "label": "OB Care Established",
        "color": "#84CC16",
        "order": 17,
        "stageType": "post_approval"
    },
    {
        "stageKey": "pbo_process_started",
        "slug": "pbo_process_started",
        "label": "PBO Process Started",
        "color": "#DB2777",
        "order": 18,
        "stageType": "post_approval"
    },
    {
        "stageKey": "anatomy_scanned",
        "slug": "anatomy_scanned",
        "label": "Anatomy Scanned",
        "color": "#16A34A",
        "order": 19,
        "stageType": "post_approval"
    },
    {
        "stageKey": "delivered",
        "slug": "delivered",
        "label": "Delivered",
        "color": "#16A34A",
        "order": 20,
        "stageType": "post_approval"
    },
    {
        "stageKey": "on_hold",
        "slug": "on_hold",
        "label": "On-Hold",
        "color": "#B4536A",
        "order": 21,
        "stageType": "paused"
    },
    {
        "stageKey": "cold_leads",
        "slug": "cold_leads",
        "label": "Cold Leads",
        "color": "#64748B",
        "order": 22,
        "stageType": "terminal"
    },
    {
        "stageKey": "lost",
        "slug": "lost",
        "label": "Lost",
        "color": "#EF4444",
        "order": 23,
        "stageType": "terminal"
    },
    {
        "stageKey": "disqualified",
        "slug": "disqualified",
        "label": "Disqualified",
        "color": "#EF4444",
        "order": 24,
        "stageType": "terminal"
    }
]

export const STAGE_TYPE_MAP: Record<string, StageType> = {
    "anatomy_scanned": "post_approval",
    "application_submitted": "intake",
    "approved": "intake",
    "cold_leads": "terminal",
    "contacted": "intake",
    "delivered": "post_approval",
    "disqualified": "terminal",
    "heartbeat_confirmed": "post_approval",
    "interview_scheduled": "intake",
    "legal_clearance_passed": "post_approval",
    "life_insurance_application_started": "post_approval",
    "lost": "terminal",
    "matched": "post_approval",
    "medical_clearance_passed": "post_approval",
    "new_unread": "intake",
    "ob_care_established": "post_approval",
    "on_hold": "paused",
    "pbo_process_started": "post_approval",
    "pending_docusign": "intake",
    "pre_qualified": "intake",
    "ready_to_match": "post_approval",
    "second_hcg_confirmed": "post_approval",
    "transfer_cycle": "post_approval",
    "under_review": "intake"
}

export const DEFAULT_STAGE_ORDER: string[] = [
    "new_unread",
    "contacted",
    "pre_qualified",
    "application_submitted",
    "interview_scheduled",
    "pending_docusign",
    "under_review",
    "approved",
    "ready_to_match",
    "matched",
    "medical_clearance_passed",
    "legal_clearance_passed",
    "transfer_cycle",
    "second_hcg_confirmed",
    "heartbeat_confirmed",
    "life_insurance_application_started",
    "ob_care_established",
    "pbo_process_started",
    "anatomy_scanned",
    "delivered",
    "on_hold",
    "cold_leads",
    "lost",
    "disqualified"
]

export const DEFAULT_STAGE_SEMANTICS_BY_KEY: Record<string, StageSemantics> = {
    "anatomy_scanned": {
        "analytics_bucket": "anatomy_scanned",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": true,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "anatomy_scan_followup",
        "terminal_outcome": "none"
    },
    "application_submitted": {
        "analytics_bucket": "application_submitted",
        "capabilities": {
            "counts_as_contacted": true,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "qualified",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "application_submitted_followup",
        "terminal_outcome": "none"
    },
    "approved": {
        "analytics_bucket": "approved",
        "capabilities": {
            "counts_as_contacted": true,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": true
        },
        "integration_bucket": "qualified",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "approved_followup",
        "terminal_outcome": "none"
    },
    "cold_leads": {
        "analytics_bucket": "cold_leads",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "none",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": null,
        "terminal_outcome": "none"
    },
    "contacted": {
        "analytics_bucket": "contacted",
        "capabilities": {
            "counts_as_contacted": true,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "intake",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "contacted_followup",
        "terminal_outcome": "none"
    },
    "delivered": {
        "analytics_bucket": "delivered",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": true,
            "shows_pregnancy_tracking": true,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": null,
        "terminal_outcome": "none"
    },
    "disqualified": {
        "analytics_bucket": "disqualified",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "not_qualified",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": null,
        "terminal_outcome": "disqualified"
    },
    "heartbeat_confirmed": {
        "analytics_bucket": "heartbeat_confirmed",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": true,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "heartbeat_followup",
        "terminal_outcome": "none"
    },
    "interview_scheduled": {
        "analytics_bucket": "interview_scheduled",
        "capabilities": {
            "counts_as_contacted": true,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": true
        },
        "integration_bucket": "qualified",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "interview_scheduled_followup",
        "terminal_outcome": "none"
    },
    "legal_clearance_passed": {
        "analytics_bucket": "legal_clearance_passed",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "legal_clearance_followup",
        "terminal_outcome": "none"
    },
    "life_insurance_application_started": {
        "analytics_bucket": "life_insurance_application_started",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": true,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": null,
        "terminal_outcome": "none"
    },
    "lost": {
        "analytics_bucket": "lost",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "lost",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": null,
        "terminal_outcome": "lost"
    },
    "matched": {
        "analytics_bucket": "matched",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "matched_followup",
        "terminal_outcome": "none"
    },
    "medical_clearance_passed": {
        "analytics_bucket": "medical_clearance_passed",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "medical_clearance_followup",
        "terminal_outcome": "none"
    },
    "new_unread": {
        "analytics_bucket": "new_unread",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "none",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "new_unread_followup",
        "terminal_outcome": "none"
    },
    "ob_care_established": {
        "analytics_bucket": "ob_care_established",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": true,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "ob_care_followup",
        "terminal_outcome": "none"
    },
    "on_hold": {
        "analytics_bucket": "on_hold",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "none",
        "pause_behavior": "resume_previous_stage",
        "requires_reason_on_enter": true,
        "suggestion_profile_key": null,
        "terminal_outcome": "none"
    },
    "pbo_process_started": {
        "analytics_bucket": "pbo_process_started",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": true,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": null,
        "terminal_outcome": "none"
    },
    "pending_docusign": {
        "analytics_bucket": "pending_docusign",
        "capabilities": {
            "counts_as_contacted": true,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "qualified",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": null,
        "terminal_outcome": "none"
    },
    "pre_qualified": {
        "analytics_bucket": "pre_qualified",
        "capabilities": {
            "counts_as_contacted": true,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "qualified",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "qualified_followup",
        "terminal_outcome": "none"
    },
    "ready_to_match": {
        "analytics_bucket": "ready_to_match",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": true,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "ready_to_match_followup",
        "terminal_outcome": "none"
    },
    "second_hcg_confirmed": {
        "analytics_bucket": "second_hcg_confirmed",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "second_hcg_followup",
        "terminal_outcome": "none"
    },
    "transfer_cycle": {
        "analytics_bucket": "transfer_cycle",
        "capabilities": {
            "counts_as_contacted": false,
            "eligible_for_matching": false,
            "locks_match_state": true,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": false
        },
        "integration_bucket": "converted",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "transfer_cycle_followup",
        "terminal_outcome": "none"
    },
    "under_review": {
        "analytics_bucket": "under_review",
        "capabilities": {
            "counts_as_contacted": true,
            "eligible_for_matching": false,
            "locks_match_state": false,
            "requires_delivery_details": false,
            "shows_pregnancy_tracking": false,
            "tracks_interview_outcome": true
        },
        "integration_bucket": "qualified",
        "pause_behavior": "none",
        "requires_reason_on_enter": false,
        "suggestion_profile_key": "under_review_followup",
        "terminal_outcome": "none"
    }
}
