// Generated by scripts/gen_stage_map.py. Do not edit.

export type StageType = "intake" | "post_approval" | "terminal"

export type StageDef = {
    stageKey: string
    slug: string
    label: string
    color: string
    order: number
    stageType: StageType
}

export type RoleStageRule = {
    stageTypes: StageType[]
    extraSlugs: string[]
}

export const STAGE_DEFS: StageDef[] = [
    {
        "stageKey": "new_unread",
        "slug": "new_unread",
        "label": "New Unread",
        "color": "#3B82F6",
        "order": 1,
        "stageType": "intake"
    },
    {
        "stageKey": "contacted",
        "slug": "contacted",
        "label": "Contacted",
        "color": "#06B6D4",
        "order": 2,
        "stageType": "intake"
    },
    {
        "stageKey": "pre_qualified",
        "slug": "pre_qualified",
        "label": "Pre-Qualified",
        "color": "#10B981",
        "order": 3,
        "stageType": "intake"
    },
    {
        "stageKey": "application_submitted",
        "slug": "application_submitted",
        "label": "Application Submitted",
        "color": "#8B5CF6",
        "order": 4,
        "stageType": "intake"
    },
    {
        "stageKey": "interview_scheduled",
        "slug": "interview_scheduled",
        "label": "Interview Scheduled",
        "color": "#A855F7",
        "order": 5,
        "stageType": "intake"
    },
    {
        "stageKey": "under_review",
        "slug": "under_review",
        "label": "Under Review",
        "color": "#F59E0B",
        "order": 6,
        "stageType": "intake"
    },
    {
        "stageKey": "approved",
        "slug": "approved",
        "label": "Approved",
        "color": "#22C55E",
        "order": 7,
        "stageType": "intake"
    },
    {
        "stageKey": "ready_to_match",
        "slug": "ready_to_match",
        "label": "Ready to Match",
        "color": "#0EA5E9",
        "order": 8,
        "stageType": "post_approval"
    },
    {
        "stageKey": "matched",
        "slug": "matched",
        "label": "Matched",
        "color": "#6366F1",
        "order": 9,
        "stageType": "post_approval"
    },
    {
        "stageKey": "medical_clearance_passed",
        "slug": "medical_clearance_passed",
        "label": "Medical Clearance Passed",
        "color": "#14B8A6",
        "order": 10,
        "stageType": "post_approval"
    },
    {
        "stageKey": "legal_clearance_passed",
        "slug": "legal_clearance_passed",
        "label": "Legal Clearance Passed",
        "color": "#059669",
        "order": 11,
        "stageType": "post_approval"
    },
    {
        "stageKey": "transfer_cycle",
        "slug": "transfer_cycle",
        "label": "Transfer Cycle Initiated",
        "color": "#0D9488",
        "order": 12,
        "stageType": "post_approval"
    },
    {
        "stageKey": "second_hcg_confirmed",
        "slug": "second_hcg_confirmed",
        "label": "Second hCG confirmed",
        "color": "#10B981",
        "order": 13,
        "stageType": "post_approval"
    },
    {
        "stageKey": "heartbeat_confirmed",
        "slug": "heartbeat_confirmed",
        "label": "Heartbeat Confirmed",
        "color": "#22C55E",
        "order": 14,
        "stageType": "post_approval"
    },
    {
        "stageKey": "ob_care_established",
        "slug": "ob_care_established",
        "label": "OB Care Established",
        "color": "#84CC16",
        "order": 15,
        "stageType": "post_approval"
    },
    {
        "stageKey": "anatomy_scanned",
        "slug": "anatomy_scanned",
        "label": "Anatomy Scanned",
        "color": "#16A34A",
        "order": 16,
        "stageType": "post_approval"
    },
    {
        "stageKey": "delivered",
        "slug": "delivered",
        "label": "Delivered",
        "color": "#16A34A",
        "order": 17,
        "stageType": "post_approval"
    },
    {
        "stageKey": "lost",
        "slug": "lost",
        "label": "Lost",
        "color": "#EF4444",
        "order": 18,
        "stageType": "terminal"
    },
    {
        "stageKey": "disqualified",
        "slug": "disqualified",
        "label": "Disqualified",
        "color": "#EF4444",
        "order": 19,
        "stageType": "terminal"
    }
]

export const STAGE_TYPE_MAP: Record<string, StageType> = {
    "anatomy_scanned": "post_approval",
    "application_submitted": "intake",
    "approved": "intake",
    "contacted": "intake",
    "delivered": "post_approval",
    "disqualified": "terminal",
    "heartbeat_confirmed": "post_approval",
    "interview_scheduled": "intake",
    "legal_clearance_passed": "post_approval",
    "lost": "terminal",
    "matched": "post_approval",
    "medical_clearance_passed": "post_approval",
    "new_unread": "intake",
    "ob_care_established": "post_approval",
    "pre_qualified": "intake",
    "ready_to_match": "post_approval",
    "second_hcg_confirmed": "post_approval",
    "transfer_cycle": "post_approval",
    "under_review": "intake"
}

export const DEFAULT_STAGE_ORDER: string[] = [
    "new_unread",
    "contacted",
    "pre_qualified",
    "application_submitted",
    "interview_scheduled",
    "under_review",
    "approved",
    "ready_to_match",
    "matched",
    "medical_clearance_passed",
    "legal_clearance_passed",
    "transfer_cycle",
    "second_hcg_confirmed",
    "heartbeat_confirmed",
    "ob_care_established",
    "anatomy_scanned",
    "delivered",
    "lost",
    "disqualified"
]

export const ROLE_STAGE_VISIBILITY: Record<string, RoleStageRule> = {
    "admin": {
        "extraSlugs": [],
        "stageTypes": [
            "intake",
            "post_approval",
            "terminal"
        ]
    },
    "case_manager": {
        "extraSlugs": [
            "approved",
            "lost",
            "disqualified"
        ],
        "stageTypes": [
            "post_approval"
        ]
    },
    "developer": {
        "extraSlugs": [],
        "stageTypes": [
            "intake",
            "post_approval",
            "terminal"
        ]
    },
    "intake_specialist": {
        "extraSlugs": [],
        "stageTypes": [
            "intake",
            "terminal"
        ]
    }
}

export const ROLE_STAGE_MUTATION: Record<string, RoleStageRule> = {
    "admin": {
        "extraSlugs": [],
        "stageTypes": [
            "intake",
            "post_approval",
            "terminal"
        ]
    },
    "case_manager": {
        "extraSlugs": [
            "lost",
            "disqualified"
        ],
        "stageTypes": [
            "post_approval"
        ]
    },
    "developer": {
        "extraSlugs": [],
        "stageTypes": [
            "intake",
            "post_approval",
            "terminal"
        ]
    },
    "intake_specialist": {
        "extraSlugs": [],
        "stageTypes": [
            "intake",
            "terminal"
        ]
    }
}

