#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
import json
import os
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
API_ROOT = ROOT / "apps" / "api"
WEB_OUT = ROOT / "apps" / "web" / "lib" / "constants" / "stages.generated.ts"

os.environ.setdefault("ENV", "test")
os.environ.setdefault(
    "DATABASE_URL",
    "postgresql+psycopg://user:pass@localhost:5432/crm_dev",
)

sys.path.insert(0, str(API_ROOT))

from app.core import stage_definitions  # noqa: E402


def _load_pipeline_semantics_module():
    module_path = API_ROOT / "app" / "schemas" / "pipeline_semantics.py"
    spec = importlib.util.spec_from_file_location("pipeline_semantics_for_stage_map", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load pipeline semantics module: {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


pipeline_semantics = _load_pipeline_semantics_module()


def _stage_defs() -> list[dict[str, object]]:
    stage_defs = stage_definitions.get_default_stage_defs()
    return [
        {
            "stageKey": stage["stage_key"],
            "slug": stage["slug"],
            "label": stage["label"],
            "color": stage["color"],
            "order": stage["order"],
            "stageType": stage["stage_type"],
        }
        for stage in stage_defs
    ]


def _default_stage_semantics_by_key(
    stage_defs: list[dict[str, object]],
) -> dict[str, dict[str, object]]:
    return {
        str(stage["stageKey"]): pipeline_semantics.default_stage_semantics(
            str(stage["stageKey"]),
            str(stage["stageType"]),
            stage_definitions.SURROGATE_PIPELINE_ENTITY,
        )
        for stage in stage_defs
    }


def render_typescript() -> str:
    stage_defs = _stage_defs()
    stage_type_map = dict(stage_definitions.STAGE_TYPE_MAP)
    stage_order = list(stage_definitions.DEFAULT_STAGE_ORDER)
    stage_semantics = _default_stage_semantics_by_key(stage_defs)

    stage_types = sorted({stage["stageType"] for stage in stage_defs})
    stage_type_union = (
        " | ".join(f'"{stage_type}"' for stage_type in stage_types) or "string"
    )

    return f"""// Generated by scripts/gen_stage_map.py. Do not edit.

import type {{ StageSemantics }} from "@/lib/api/pipelines"

export type StageType = {stage_type_union}

export type StageDef = {{
    stageKey: string
    slug: string
    label: string
    color: string
    order: number
    stageType: StageType
}}

export const STAGE_DEFS: StageDef[] = {json.dumps(stage_defs, indent=4)}

export const STAGE_TYPE_MAP: Record<string, StageType> = {json.dumps(stage_type_map, indent=4, sort_keys=True)}

export const DEFAULT_STAGE_ORDER: string[] = {json.dumps(stage_order, indent=4)}

export const DEFAULT_STAGE_SEMANTICS_BY_KEY: Record<string, StageSemantics> = {json.dumps(stage_semantics, indent=4, sort_keys=True)}
"""


def main() -> None:
    WEB_OUT.parent.mkdir(parents=True, exist_ok=True)
    WEB_OUT.write_text(render_typescript(), encoding="utf-8")


if __name__ == "__main__":
    main()
