#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
API_ROOT = ROOT / "apps" / "api"
WEB_OUT = ROOT / "apps" / "web" / "lib" / "constants" / "stages.generated.ts"

os.environ.setdefault("ENV", "test")
os.environ.setdefault(
    "DATABASE_URL",
    "postgresql+psycopg://user:pass@localhost:5432/crm_dev",
)

sys.path.insert(0, str(API_ROOT))

from app.core import stage_definitions  # noqa: E402


def _stage_defs() -> list[dict[str, object]]:
    stage_defs = stage_definitions.get_default_stage_defs()
    return [
        {
            "stageKey": stage["stage_key"],
            "slug": stage["slug"],
            "label": stage["label"],
            "color": stage["color"],
            "order": stage["order"],
            "stageType": stage["stage_type"],
        }
        for stage in stage_defs
    ]


def main() -> None:
    stage_defs = _stage_defs()
    stage_type_map = dict(stage_definitions.STAGE_TYPE_MAP)
    stage_order = list(stage_definitions.DEFAULT_STAGE_ORDER)

    stage_types = sorted({stage["stageType"] for stage in stage_defs})
    stage_type_union = (
        " | ".join(f'"{stage_type}"' for stage_type in stage_types) or "string"
    )

    ts_output = f"""// Generated by scripts/gen_stage_map.py. Do not edit.

export type StageType = {stage_type_union}

export type StageDef = {{
    stageKey: string
    slug: string
    label: string
    color: string
    order: number
    stageType: StageType
}}

export const STAGE_DEFS: StageDef[] = {json.dumps(stage_defs, indent=4)}

export const STAGE_TYPE_MAP: Record<string, StageType> = {json.dumps(stage_type_map, indent=4, sort_keys=True)}

export const DEFAULT_STAGE_ORDER: string[] = {json.dumps(stage_order, indent=4)}
"""

    WEB_OUT.parent.mkdir(parents=True, exist_ok=True)
    WEB_OUT.write_text(ts_output + "\n")


if __name__ == "__main__":
    main()
