"""Stable notification imports for domain services."""

from app.services import notification_service

create_notification = notification_service.create_notification
notify_appointment_cancelled = notification_service.notify_appointment_cancelled
notify_appointment_confirmed = notification_service.notify_appointment_confirmed
notify_appointment_requested = notification_service.notify_appointment_requested
notify_ip_status_change_request_pending = notification_service.notify_ip_status_change_request_pending
notify_ip_status_change_request_resolved = notification_service.notify_ip_status_change_request_resolved
notify_match_cancel_request_pending = notification_service.notify_match_cancel_request_pending
notify_match_cancel_request_resolved = notification_service.notify_match_cancel_request_resolved
notify_status_change_request_pending = notification_service.notify_status_change_request_pending
notify_status_change_request_resolved = notification_service.notify_status_change_request_resolved
notify_surrogate_assigned = notification_service.notify_surrogate_assigned
notify_surrogate_ready_for_claim = notification_service.notify_surrogate_ready_for_claim
notify_surrogate_status_changed = notification_service.notify_surrogate_status_changed
notify_task_assigned = notification_service.notify_task_assigned
notify_workflow_approval_requested = notification_service.notify_workflow_approval_requested
should_notify = notification_service.should_notify
