"""Signature enhancement: org branding and user social links

Revision ID: 0afc5c98c589
Revises: h1b2c3d4e5f6
Create Date: 2026-01-05 10:45:33.439184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afc5c98c589'
down_revision: Union[str, Sequence[str], None] = 'h1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Organization signature branding fields
    op.add_column('organizations', sa.Column('signature_template', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('signature_logo_url', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('signature_primary_color', sa.String(length=7), nullable=True))
    op.add_column('organizations', sa.Column('signature_company_name', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('signature_address', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('signature_phone', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('signature_website', sa.String(length=255), nullable=True))
    
    # User social link fields (replacing legacy signature fields)
    op.add_column('users', sa.Column('signature_linkedin', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('signature_twitter', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('signature_instagram', sa.String(length=255), nullable=True))
    
    # Drop legacy user signature columns
    op.drop_column('users', 'signature_name')
    op.drop_column('users', 'signature_phone')
    op.drop_column('users', 'signature_website')
    op.drop_column('users', 'signature_html')
    op.drop_column('users', 'signature_company')
    op.drop_column('users', 'signature_email')
    op.drop_column('users', 'signature_address')
    op.drop_column('users', 'signature_logo_url')
    op.drop_column('users', 'signature_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add legacy user signature columns
    op.add_column('users', sa.Column('signature_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signature_logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signature_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signature_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signature_company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signature_html', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signature_website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signature_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signature_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    
    # Drop user social link columns
    op.drop_column('users', 'signature_instagram')
    op.drop_column('users', 'signature_twitter')
    op.drop_column('users', 'signature_linkedin')
    
    # Drop organization signature columns
    op.drop_column('organizations', 'signature_website')
    op.drop_column('organizations', 'signature_phone')
    op.drop_column('organizations', 'signature_address')
    op.drop_column('organizations', 'signature_company_name')
    op.drop_column('organizations', 'signature_primary_color')
    op.drop_column('organizations', 'signature_logo_url')
    op.drop_column('organizations', 'signature_template')
    # ### end Alembic commands ###

