"""fix: Update automation workflows schema - NOT NULL constraints and indexes

Revision ID: 201ff7c41d70
Revises: 0030_ip_owner_model
Create Date: 2025-12-19 05:33:43.034685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "201ff7c41d70"
down_revision: Union[str, Sequence[str], None] = "0030_ip_owner_model"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "automation_workflows",
        "icon",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'workflow'::character varying"),
    )
    op.alter_column(
        "automation_workflows",
        "schema_version",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "automation_workflows",
        "conditions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "automation_workflows",
        "condition_logic",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
        existing_server_default=sa.text("'AND'::character varying"),
    )
    op.alter_column(
        "automation_workflows",
        "is_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "automation_workflows",
        "run_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index(
        op.f("idx_wf_trigger"),
        table_name="automation_workflows",
        postgresql_where="(is_enabled = true)",
    )
    op.drop_column("automation_workflows", "condition_field_list")
    op.alter_column(
        "user_workflow_preferences",
        "is_opted_out",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "workflow_executions",
        "depth",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "workflow_executions",
        "matched_conditions",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "workflow_executions",
        "actions_executed",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_index(op.f("idx_exec_status"), table_name="workflow_executions")
    op.drop_index(
        op.f("uq_exec_dedupe"),
        table_name="workflow_executions",
        postgresql_where="(dedupe_key IS NOT NULL)",
    )
    op.drop_index(op.f("idx_exec_workflow"), table_name="workflow_executions")
    op.create_index(
        "idx_exec_workflow",
        "workflow_executions",
        ["workflow_id", "executed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_exec_workflow", table_name="workflow_executions")
    op.create_index(
        op.f("idx_exec_workflow"),
        "workflow_executions",
        ["workflow_id", sa.literal_column("executed_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("uq_exec_dedupe"),
        "workflow_executions",
        ["dedupe_key"],
        unique=True,
        postgresql_where="(dedupe_key IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_exec_status"),
        "workflow_executions",
        ["organization_id", "status", sa.literal_column("executed_at DESC")],
        unique=False,
    )
    op.alter_column(
        "workflow_executions",
        "actions_executed",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "workflow_executions",
        "matched_conditions",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "workflow_executions",
        "depth",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "user_workflow_preferences",
        "is_opted_out",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.add_column(
        "automation_workflows",
        sa.Column(
            "condition_field_list",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("idx_wf_trigger"),
        "automation_workflows",
        ["organization_id", "trigger_type"],
        unique=False,
        postgresql_where="(is_enabled = true)",
    )
    op.alter_column(
        "automation_workflows",
        "run_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "automation_workflows",
        "is_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "automation_workflows",
        "condition_logic",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
        existing_server_default=sa.text("'AND'::character varying"),
    )
    op.alter_column(
        "automation_workflows",
        "conditions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "automation_workflows",
        "schema_version",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "automation_workflows",
        "icon",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'workflow'::character varying"),
    )
    # ### end Alembic commands ###
