"""add_campaign_include_unsubscribed

Revision ID: 20260206_1031
Revises: 20260202_1148
Create Date: 2026-02-06 10:31:46.622334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260206_1031'
down_revision: Union[str, Sequence[str], None] = '20260202_1148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('include_unsubscribed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'include_unsubscribed')
    # ### end Alembic commands ###
