"""Add donor demographics, personal information, medical records and screening answers.

Revision ID: 20260914_1200_donor_profile
Revises: 20260905_1600_record_integrations
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "20260914_1200_donor_profile"
down_revision = "20260905_1600_record_integrations"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '3s'")
    op.execute("SET LOCAL statement_timeout = '60s'")
    for column in (
        sa.Column("marital_status", sa.String(100), nullable=True),
        sa.Column("ssn", sa.Text(), nullable=True),
        sa.Column("ssn_last4", sa.String(4), nullable=True),
        sa.Column("address_line1", sa.Text(), nullable=True),
        sa.Column("address_line2", sa.Text(), nullable=True),
        sa.Column("address_city", sa.String(100), nullable=True),
        sa.Column("address_state", sa.String(2), nullable=True),
        sa.Column("address_postal", sa.String(20), nullable=True),
        sa.Column("partner_name", sa.String(255), nullable=True),
        sa.Column("partner_date_of_birth", sa.Text(), nullable=True),
        sa.Column("partner_email", sa.Text(), nullable=True),
        sa.Column("partner_phone", sa.Text(), nullable=True),
        sa.Column("partner_ssn", sa.Text(), nullable=True),
        sa.Column("partner_ssn_last4", sa.String(4), nullable=True),
        sa.Column("partner_address_line1", sa.Text(), nullable=True),
        sa.Column("partner_address_line2", sa.Text(), nullable=True),
        sa.Column("partner_city", sa.String(100), nullable=True),
        sa.Column("partner_state", sa.String(2), nullable=True),
        sa.Column("partner_postal", sa.String(20), nullable=True),
        sa.Column("date_of_birth", sa.Text(), nullable=True),
        sa.Column("race", sa.String(100), nullable=True),
        sa.Column("height_ft", sa.Numeric(4, 2), nullable=True),
        sa.Column("weight_lb", sa.Integer(), nullable=True),
        sa.Column("insurance_company", sa.String(255), nullable=True),
        sa.Column("insurance_plan_name", sa.String(255), nullable=True),
        sa.Column("insurance_phone", sa.Text(), nullable=True),
        sa.Column("insurance_policy_number", sa.Text(), nullable=True),
        sa.Column("insurance_member_id", sa.Text(), nullable=True),
        sa.Column("insurance_group_number", sa.String(100), nullable=True),
        sa.Column("insurance_subscriber_name", sa.Text(), nullable=True),
        sa.Column("insurance_subscriber_dob", sa.Text(), nullable=True),
        sa.Column("insurance_fax", sa.Text(), nullable=True),
        sa.Column("clinic_name", sa.String(255), nullable=True),
        sa.Column("clinic_address_line1", sa.Text(), nullable=True),
        sa.Column("clinic_address_line2", sa.Text(), nullable=True),
        sa.Column("clinic_city", sa.String(100), nullable=True),
        sa.Column("clinic_state", sa.String(2), nullable=True),
        sa.Column("clinic_postal", sa.String(20), nullable=True),
        sa.Column("clinic_phone", sa.Text(), nullable=True),
        sa.Column("clinic_email", sa.Text(), nullable=True),
        sa.Column("clinic_fax", sa.Text(), nullable=True),
        sa.Column("monitoring_clinic_name", sa.String(255), nullable=True),
        sa.Column("monitoring_clinic_address_line1", sa.Text(), nullable=True),
        sa.Column("monitoring_clinic_address_line2", sa.Text(), nullable=True),
        sa.Column("monitoring_clinic_city", sa.String(100), nullable=True),
        sa.Column("monitoring_clinic_state", sa.String(2), nullable=True),
        sa.Column("monitoring_clinic_postal", sa.String(20), nullable=True),
        sa.Column("monitoring_clinic_phone", sa.Text(), nullable=True),
        sa.Column("monitoring_clinic_email", sa.Text(), nullable=True),
        sa.Column("monitoring_clinic_fax", sa.Text(), nullable=True),
        sa.Column("ob_provider_name", sa.String(255), nullable=True),
        sa.Column("ob_clinic_name", sa.String(255), nullable=True),
        sa.Column("ob_address_line1", sa.Text(), nullable=True),
        sa.Column("ob_address_line2", sa.Text(), nullable=True),
        sa.Column("ob_city", sa.String(100), nullable=True),
        sa.Column("ob_state", sa.String(2), nullable=True),
        sa.Column("ob_postal", sa.String(20), nullable=True),
        sa.Column("ob_phone", sa.Text(), nullable=True),
        sa.Column("ob_email", sa.Text(), nullable=True),
        sa.Column("ob_fax", sa.Text(), nullable=True),
        sa.Column("delivery_hospital_name", sa.String(255), nullable=True),
        sa.Column("delivery_hospital_address_line1", sa.Text(), nullable=True),
        sa.Column("delivery_hospital_address_line2", sa.Text(), nullable=True),
        sa.Column("delivery_hospital_city", sa.String(100), nullable=True),
        sa.Column("delivery_hospital_state", sa.String(2), nullable=True),
        sa.Column("delivery_hospital_postal", sa.String(20), nullable=True),
        sa.Column("delivery_hospital_phone", sa.Text(), nullable=True),
        sa.Column("delivery_hospital_email", sa.Text(), nullable=True),
        sa.Column("delivery_hospital_fax", sa.Text(), nullable=True),
        sa.Column("pcp_provider_name", sa.String(255), nullable=True),
        sa.Column("pcp_name", sa.String(255), nullable=True),
        sa.Column("pcp_address_line1", sa.Text(), nullable=True),
        sa.Column("pcp_address_line2", sa.Text(), nullable=True),
        sa.Column("pcp_city", sa.String(100), nullable=True),
        sa.Column("pcp_state", sa.String(2), nullable=True),
        sa.Column("pcp_postal", sa.String(20), nullable=True),
        sa.Column("pcp_phone", sa.Text(), nullable=True),
        sa.Column("pcp_fax", sa.Text(), nullable=True),
        sa.Column("pcp_email", sa.Text(), nullable=True),
        sa.Column("lab_clinic_name", sa.String(255), nullable=True),
        sa.Column("lab_clinic_address_line1", sa.Text(), nullable=True),
        sa.Column("lab_clinic_address_line2", sa.Text(), nullable=True),
        sa.Column("lab_clinic_city", sa.String(100), nullable=True),
        sa.Column("lab_clinic_state", sa.String(2), nullable=True),
        sa.Column("lab_clinic_postal", sa.String(20), nullable=True),
        sa.Column("lab_clinic_phone", sa.Text(), nullable=True),
        sa.Column("lab_clinic_fax", sa.Text(), nullable=True),
        sa.Column("lab_clinic_email", sa.Text(), nullable=True),
        sa.Column("college", sa.Text(), nullable=True),
        sa.Column("nicotine", sa.Text(), nullable=True),
        sa.Column("cannabis", sa.Text(), nullable=True),
        sa.Column("infectious_disease", sa.Text(), nullable=True),
        sa.Column("previous_donation", sa.Text(), nullable=True),
        sa.Column(
            "profile_updated_fields",
            postgresql.JSONB(),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    ):
        op.add_column("donors", column)


def downgrade() -> None:
    for name in (
        "profile_updated_fields",
        "previous_donation",
        "infectious_disease",
        "cannabis",
        "nicotine",
        "college",
        "lab_clinic_email",
        "lab_clinic_fax",
        "lab_clinic_phone",
        "lab_clinic_postal",
        "lab_clinic_state",
        "lab_clinic_city",
        "lab_clinic_address_line2",
        "lab_clinic_address_line1",
        "lab_clinic_name",
        "pcp_email",
        "pcp_fax",
        "pcp_phone",
        "pcp_postal",
        "pcp_state",
        "pcp_city",
        "pcp_address_line2",
        "pcp_address_line1",
        "pcp_name",
        "pcp_provider_name",
        "delivery_hospital_fax",
        "delivery_hospital_email",
        "delivery_hospital_phone",
        "delivery_hospital_postal",
        "delivery_hospital_state",
        "delivery_hospital_city",
        "delivery_hospital_address_line2",
        "delivery_hospital_address_line1",
        "delivery_hospital_name",
        "ob_fax",
        "ob_email",
        "ob_phone",
        "ob_postal",
        "ob_state",
        "ob_city",
        "ob_address_line2",
        "ob_address_line1",
        "ob_clinic_name",
        "ob_provider_name",
        "monitoring_clinic_fax",
        "monitoring_clinic_email",
        "monitoring_clinic_phone",
        "monitoring_clinic_postal",
        "monitoring_clinic_state",
        "monitoring_clinic_city",
        "monitoring_clinic_address_line2",
        "monitoring_clinic_address_line1",
        "monitoring_clinic_name",
        "clinic_fax",
        "clinic_email",
        "clinic_phone",
        "clinic_postal",
        "clinic_state",
        "clinic_city",
        "clinic_address_line2",
        "clinic_address_line1",
        "clinic_name",
        "insurance_fax",
        "insurance_subscriber_dob",
        "insurance_subscriber_name",
        "insurance_group_number",
        "insurance_member_id",
        "insurance_policy_number",
        "insurance_phone",
        "insurance_plan_name",
        "insurance_company",
        "weight_lb",
        "height_ft",
        "race",
        "date_of_birth",
        "partner_postal",
        "partner_state",
        "partner_city",
        "partner_address_line2",
        "partner_address_line1",
        "partner_ssn_last4",
        "partner_ssn",
        "partner_phone",
        "partner_email",
        "partner_date_of_birth",
        "partner_name",
        "address_postal",
        "address_state",
        "address_city",
        "address_line2",
        "address_line1",
        "ssn_last4",
        "ssn",
        "marital_status",
    ):
        op.drop_column("donors", name)
