"""add messaging delivery core

Revision ID: 20260731_2230
Revises: 20260731_2220
Create Date: 2026-07-31 17:12:07.050427

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.db.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260731_2230"
down_revision: str | Sequence[str] | None = "20260731_2220"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messaging_provider_admission",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("account_sid_hash", sa.String(length=64), nullable=False),
        sa.Column("next_slot_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_sid_hash", name="uq_messaging_provider_admission_account"),
    )
    op.create_index(
        "idx_messaging_provider_next_slot",
        "messaging_provider_admission",
        ["next_slot_at"],
        unique=False,
    )
    op.create_table(
        "message_media_assets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", app.db.types.EncryptedString(), nullable=True),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "scan_status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("quarantine_reason", sa.String(length=120), nullable=True),
        sa.Column(
            "content_classification",
            sa.String(length=20),
            server_default=sa.text("'no_phi'"),
            nullable=False,
        ),
        sa.Column("provider_media_sid", sa.String(length=64), nullable=True),
        sa.Column("provider_deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_classification IN ('no_phi', 'phi')", name="ck_message_media_classification"
        ),
        sa.CheckConstraint(
            "scan_status IN ('pending', 'clean', 'quarantined', 'rejected')",
            name="ck_message_media_scan_status",
        ),
        sa.CheckConstraint("byte_size >= 0", name="ck_message_media_size"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "checksum_sha256", name="uq_message_media_checksum"),
    )
    op.create_index(
        "idx_message_media_org_scan",
        "message_media_assets",
        ["organization_id", "scan_status"],
        unique=False,
    )
    op.create_table(
        "message_templates",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("template_key", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("body_encrypted", app.db.types.EncryptedText(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column(
            "is_enrollment_confirmation",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "content_classification",
            sa.String(length=20),
            server_default=sa.text("'no_phi'"),
            nullable=False,
        ),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_classification IN ('no_phi', 'phi')",
            name="ck_message_templates_classification",
        ),
        sa.CheckConstraint(
            "purpose IN ('operational', 'promotional')", name="ck_message_templates_purpose"
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'retired')", name="ck_message_templates_status"
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "template_key", "version", name="uq_message_template_version"
        ),
    )
    op.create_index(
        "idx_message_templates_org_status",
        "message_templates",
        ["organization_id", "status", "purpose"],
        unique=False,
    )
    op.create_table(
        "message_webhook_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("account_sid_hash", sa.String(length=64), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("provider_message_sid", sa.String(length=64), nullable=False),
        sa.Column("provider_status", sa.String(length=40), nullable=True),
        sa.Column("raw_fields_encrypted", app.db.types.EncryptedText(), nullable=False),
        sa.Column(
            "received_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "event_type IN ('inbound', 'status')", name="ck_message_webhook_event_type"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["twilio_routes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_sid_hash", "event_key", name="uq_message_webhook_event"),
    )
    op.create_index(
        "idx_message_webhook_message_sid",
        "message_webhook_events",
        ["organization_id", "provider_message_sid"],
        unique=False,
    )
    op.create_index(
        "idx_message_webhook_org_received",
        "message_webhook_events",
        ["organization_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "messaging_conversations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("unread_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_message_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["messaging_contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["twilio_routes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "contact_id", "route_id", name="uq_messaging_conversation_route"
        ),
    )
    op.create_index(
        "idx_messaging_conversations_org_activity",
        "messaging_conversations",
        ["organization_id", "last_message_at"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("body_encrypted", app.db.types.EncryptedText(), nullable=False),
        sa.Column("provider_message_sid", sa.String(length=64), nullable=True),
        sa.Column("from_phone_hash", sa.String(length=64), nullable=False),
        sa.Column("from_phone_last4", sa.String(length=4), nullable=False),
        sa.Column("to_phone_hash", sa.String(length=64), nullable=False),
        sa.Column("to_phone_last4", sa.String(length=4), nullable=False),
        sa.Column("provider_status", sa.String(length=40), nullable=True),
        sa.Column("is_unread", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("direction IN ('inbound', 'outbound')", name="ck_messages_direction"),
        sa.CheckConstraint("purpose IN ('operational', 'promotional')", name="ck_messages_purpose"),
        sa.ForeignKeyConstraint(["contact_id"], ["messaging_contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["messaging_conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["twilio_routes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_messages_org_id"),
    )
    op.create_index(
        "idx_messages_conversation_time",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_messages_provider_sid",
        "messages",
        ["organization_id", "provider_message_sid"],
        unique=True,
        postgresql_where=sa.text("provider_message_sid IS NOT NULL"),
    )
    op.create_table(
        "message_deliveries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("template_version_id", sa.UUID(), nullable=True),
        sa.Column("consent_evidence_id", sa.UUID(), nullable=True),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("payload_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "is_enrollment_confirmation",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "status", sa.String(length=30), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "run_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column("lease_generation", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("provider_message_sid", sa.String(length=64), nullable=True),
        sa.Column("last_error_type", sa.String(length=100), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'leased' AND lease_token IS NOT NULL AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL) OR (status <> 'leased' AND lease_token IS NULL AND lease_owner IS NULL AND lease_expires_at IS NULL)",
            name="ck_message_delivery_lease_coherence",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'leased', 'retry_scheduled', 'submitted', 'delivered', 'failed', 'cancelled', 'reconciliation_required')",
            name="ck_message_deliveries_status",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts >= 1 AND attempt_count <= max_attempts",
            name="ck_message_delivery_attempt_bounds",
        ),
        sa.ForeignKeyConstraint(
            ["consent_evidence_id"], ["messaging_consent_evidence.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["messaging_contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["twilio_routes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["template_version_id"], ["message_templates.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", name="uq_message_delivery_message"),
        sa.UniqueConstraint("organization_id", "id", name="uq_message_deliveries_org_id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_message_delivery_idempotency"
        ),
    )
    op.create_index(
        "idx_message_deliveries_due",
        "message_deliveries",
        ["status", "run_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'retry_scheduled')"),
    )
    op.create_index(
        "idx_message_deliveries_org_created",
        "message_deliveries",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_message_delivery_enrollment_epoch",
        "message_deliveries",
        ["organization_id", "contact_id", "purpose", "consent_evidence_id"],
        unique=True,
        postgresql_where=sa.text(
            "is_enrollment_confirmation = true AND consent_evidence_id IS NOT NULL "
            "AND status NOT IN ('failed', 'cancelled')"
        ),
    )
    op.create_table(
        "message_media_links",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("media_asset_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_asset_id"], ["message_media_assets.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "media_asset_id", name="uq_message_media_asset"),
        sa.UniqueConstraint("message_id", "position", name="uq_message_media_position"),
    )
    op.create_table(
        "message_delivery_attempts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=False),
        sa.Column("lease_generation", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "outcome", sa.String(length=30), server_default=sa.text("'in_progress'"), nullable=False
        ),
        sa.Column("provider_http_status", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("provider_message_sid", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('in_progress', 'succeeded', 'retryable_error', 'terminal_error', 'ambiguous', 'lease_expired')",
            name="ck_message_attempt_outcome",
        ),
        sa.CheckConstraint("attempt_number >= 1", name="ck_message_attempt_number"),
        sa.ForeignKeyConstraint(
            ["organization_id", "delivery_id"],
            ["message_deliveries.organization_id", "message_deliveries.id"],
            name="fk_message_attempt_org_delivery",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_id", "attempt_number", name="uq_message_attempt_number"),
    )
    op.create_index(
        "idx_message_attempt_delivery",
        "message_delivery_attempts",
        ["organization_id", "delivery_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "message_reconciliation_cases",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("case_type", sa.String(length=40), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=True),
        sa.Column("webhook_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "detected_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("resolution_code", sa.String(length=80), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "case_type IN ('ambiguous_delivery', 'orphan_webhook', 'unlinked_inbound')",
            name="ck_message_reconciliation_case_type",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'action_required', 'resolved', 'dismissed')",
            name="ck_message_reconciliation_status",
        ),
        sa.ForeignKeyConstraint(["delivery_id"], ["message_deliveries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["webhook_event_id"], ["message_webhook_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_message_reconciliation_org_status",
        "message_reconciliation_cases",
        ["organization_id", "status", "detected_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_message_reconciliation_org_status", table_name="message_reconciliation_cases"
    )
    op.drop_table("message_reconciliation_cases")
    op.drop_index("idx_message_attempt_delivery", table_name="message_delivery_attempts")
    op.drop_table("message_delivery_attempts")
    op.drop_table("message_media_links")
    op.drop_index(
        "uq_message_delivery_enrollment_epoch",
        table_name="message_deliveries",
        postgresql_where=sa.text(
            "is_enrollment_confirmation = true AND consent_evidence_id IS NOT NULL "
            "AND status NOT IN ('failed', 'cancelled')"
        ),
    )
    op.drop_index("idx_message_deliveries_org_created", table_name="message_deliveries")
    op.drop_index(
        "idx_message_deliveries_due",
        table_name="message_deliveries",
        postgresql_where=sa.text("status IN ('pending', 'retry_scheduled')"),
    )
    op.drop_table("message_deliveries")
    op.drop_index(
        "uq_messages_provider_sid",
        table_name="messages",
        postgresql_where=sa.text("provider_message_sid IS NOT NULL"),
    )
    op.drop_index("idx_messages_conversation_time", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_messaging_conversations_org_activity", table_name="messaging_conversations")
    op.drop_table("messaging_conversations")
    op.drop_index("idx_message_webhook_org_received", table_name="message_webhook_events")
    op.drop_index("idx_message_webhook_message_sid", table_name="message_webhook_events")
    op.drop_table("message_webhook_events")
    op.drop_index("idx_message_templates_org_status", table_name="message_templates")
    op.drop_table("message_templates")
    op.drop_index("idx_message_media_org_scan", table_name="message_media_assets")
    op.drop_table("message_media_assets")
    op.drop_index("idx_messaging_provider_next_slot", table_name="messaging_provider_admission")
    op.drop_table("messaging_provider_admission")
    # ### end Alembic commands ###
