"""add_notification_settings_new_fields

Revision ID: 32f6855c0777
Revises: b0c7fdaa4a94
Create Date: 2025-12-23 18:29:11.822398

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32f6855c0777"
down_revision: Union[str, Sequence[str], None] = "b0c7fdaa4a94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_notification_settings",
        sa.Column(
            "task_reminders",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "user_notification_settings",
        sa.Column(
            "appointments", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_notification_settings", "appointments")
    op.drop_column("user_notification_settings", "task_reminders")
    # ### end Alembic commands ###
