"""Add workflow rate limit fields

Revision ID: d70f9ed6bfe6
Revises: cbad3b9adf61
Create Date: 2025-12-25 04:12:00.204312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70f9ed6bfe6'
down_revision: Union[str, Sequence[str], None] = 'cbad3b9adf61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add rate limit columns
    op.add_column('automation_workflows', sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True))
    op.add_column('automation_workflows', sa.Column('rate_limit_per_entity_per_day', sa.Integer(), nullable=True))
    
    # Drop legacy indexes if they exist (may not exist in fresh installs)
    op.execute("DROP INDEX IF EXISTS uq_workflow_system_key")
    op.execute("DROP INDEX IF EXISTS uq_email_template_system_key")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_email_template_system_key'), 'email_templates', ['organization_id', 'system_key'], unique=True, postgresql_where='(system_key IS NOT NULL)')
    op.create_index(op.f('uq_workflow_system_key'), 'automation_workflows', ['organization_id', 'system_key'], unique=True, postgresql_where='(system_key IS NOT NULL)')
    op.drop_column('automation_workflows', 'rate_limit_per_entity_per_day')
    op.drop_column('automation_workflows', 'rate_limit_per_hour')
    # ### end Alembic commands ###
