"""add_intended_parent_id_to_tasks_and_attachments

Revision ID: f0db6749d310
Revises: 866add7e8baa
Create Date: 2025-12-22 23:51:07.867166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0db6749d310"
down_revision: Union[str, Sequence[str], None] = "866add7e8baa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attachments", sa.Column("intended_parent_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        "idx_attachments_intended_parent",
        "attachments",
        ["intended_parent_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "attachments",
        "intended_parents",
        ["intended_parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("tasks", sa.Column("intended_parent_id", sa.UUID(), nullable=True))
    op.create_index(
        "idx_tasks_intended_parent", "tasks", ["intended_parent_id"], unique=False
    )
    op.create_foreign_key(
        None,
        "tasks",
        "intended_parents",
        ["intended_parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_index("idx_tasks_intended_parent", table_name="tasks")
    op.drop_column("tasks", "intended_parent_id")
    op.drop_constraint(None, "attachments", type_="foreignkey")
    op.drop_index("idx_attachments_intended_parent", table_name="attachments")
    op.drop_column("attachments", "intended_parent_id")
    # ### end Alembic commands ###
