"""add_import_mapping_corrections

Revision ID: faed99d040d9
Revises: 20260129_2100
Create Date: 2026-01-28 23:55:37.203386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "faed99d040d9"
down_revision: Union[str, Sequence[str], None] = "20260129_2100"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_mapping_corrections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("column_name_normalized", sa.String(length=255), nullable=False),
        sa.Column("original_suggestion", sa.String(length=100), nullable=True),
        sa.Column("corrected_field", sa.String(length=100), nullable=True),
        sa.Column("corrected_transformation", sa.String(length=50), nullable=True),
        sa.Column(
            "corrected_action",
            sa.String(length=20),
            server_default=sa.text("'map'"),
            nullable=False,
        ),
        sa.Column("times_used", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "column_name_normalized", name="uq_import_correction_org_col"
        ),
    )
    op.create_index(
        "idx_import_corrections_org",
        "import_mapping_corrections",
        ["organization_id"],
        unique=False,
    )
    op.add_column(
        "surrogate_imports",
        sa.Column(
            "original_suggestions_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surrogate_imports", "original_suggestions_snapshot")
    op.drop_index("idx_import_corrections_org", table_name="import_mapping_corrections")
    op.drop_table("import_mapping_corrections")
    # ### end Alembic commands ###
